name: Run Markdown Update Script

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python requirements
        working-directory: ./scripts
        run: pip install -r requirements.txt
      
      - name: Update markdown
        working-directory: ./scripts
        run: python render_map.py > ../ecosystem_map.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Markdown update 
          add-paths: |
            *.md

